Todoapp
rakesh-1010/todoappp pull request #1
Opened 2018-01-11 12:55 UTC by rakesh-1010

2018-01-16 11:58 UTC, saichander requested changes

2018-01-16 11:58 UTC, saichander commented on .idea/.generators
> +<?xml version="1.0" encoding="UTF-8"?>
@rakesh-1010 can you add these files to .gitignore

2018-01-16 11:58 UTC, saichander commented on README.rdoc
> +== README
@rakesh-1010 If you have some time at the end, can you update the readme file to include how to setup this app

2018-01-16 11:58 UTC, saichander commented on app/assets/javascripts/tasks.js
> +      $.ajax({
@rakesh-1010 Instead of having two ajax calls, you can do this using one ajax call, but you will be sending different data based on checkbox value

2018-01-16 11:58 UTC, saichander commented on app/assets/stylesheets/select2-bootstrap.css
> +
@rakesh-1010 try to use bootstrap gem, instead of including all these files

2018-01-16 11:58 UTC, saichander commented on app/controllers/comments_controller.rb
> +  before_action :set_task,only: [:new,:create,:update,:edit]
@rakesh-1010 always add space after comma, that would be more readable

2018-01-16 11:58 UTC, saichander commented on app/controllers/comments_controller.rb
> +  def edit
@rakesh-1010 remove unused actions and its routes

2018-01-16 11:58 UTC, saichander commented on app/controllers/comments_controller.rb
> +    @comment.save!
@rakesh-1010 save! will raise error, if it is unable to save the record, which would break the page, for your use case you just have to do @comment.save, which would return false if it failed to save the record, you can show errors based on that by rendering the view

2018-01-16 11:58 UTC, saichander commented on app/controllers/tasks_controller.rb
> +  before_action :authenticate_user!
@rakesh-1010 you can move this to application controller, instead of including it in every controller

2018-01-16 11:58 UTC, saichander commented on app/controllers/tasks_controller.rb
> +    @taging.remove_tag if @taging.present?
@rakesh-1010 I didn't understand what you did here, your are adding tag if tagging is not present before, and in the next step you are removing tag if taging is present(which would be always true as you are creating a tag in the previous step itself)

2018-01-16 11:58 UTC, saichander commented on app/models/taging.rb
> +  def self.add_tag(user_id,task_id,user_name)
@rakesh-1010 why do you need user_name here, you can get it from user record right?

2018-01-16 11:58 UTC, saichander commented on app/views/comments/_comments_row.html.haml
> +    %span.name-circle{title: "#{comment.user.name.upcase}"} #{comment.user.name[0].capitalize if comment.user_id.present?}
@rakesh-1010 Ideally there should not be any comment without any user_id, add that validation, and cleanup code here

2018-01-16 11:58 UTC, saichander commented on app/views/comments/_form.html.haml
> +  - if @comment.errors.any?
@rakesh-1010 can you move displaying errors related code to shared partial which accepts object(in this case @comment)

2018-01-16 11:58 UTC, saichander commented on app/views/tasks/_form.html.haml
> +  - if @task.errors.any?
@rakesh-1010 you can use the errors partial even here

2018-01-18 13:09 UTC, abhilash4252 commented on app/controllers/comments_controller.rb
> +  before_action :authenticate_user!
@rakesh-1010 You can remove this check from here because you are already checking it in ApplicationController

2018-01-18 13:09 UTC, abhilash4252 commented on app/controllers/comments_controller.rb
> +  before_action :set_comment,only: [:edit,:update,:destroy]
@rakesh-1010 
Just a suggestion, Try to use space after ',' 
I would prefer to write this as
`before_action: set_comment, only: [:edit, :update, :destroy]`

2018-01-18 13:09 UTC, abhilash4252 commented on app/controllers/comments_controller.rb
> +    @comment = @task.comments.build(comments_params)
@rakesh-1010  I would name `comments_params` as `comment_params` as you only deal with single comment object.

2018-01-18 13:09 UTC, abhilash4252 commented on app/controllers/comments_controller.rb
> +    @comment.save
@rakesh-1010 
I really don't know the flow but i would recommend you to handle error cases.

2018-01-18 13:09 UTC, abhilash4252 commented on app/controllers/tasks_controller.rb
> +  before_action :set_task, only: [:show, :edit, :update, :destroy,:change_task_state,:tag_user]
@rakesh-1010 
You can use except so that you need to list only 3 methods in before_action :set_task

2018-01-18 13:09 UTC, abhilash4252 commented on spec/models/comment_spec.rb
> +  describe 'Respond to fields' do
@rakesh-1010 
```
[:comment. :user_id, :task_id].each do |attribute|
  it "should respond to #{attribute}" do
   end
end
```

2018-01-18 13:09 UTC, abhilash4252 commented on spec/models/taging_spec.rb
> +    @comment = Taging.create(user_id: 3,task_id: 10)
@rakesh-1010  Try FactoryGirl and refactor the test cases

2018-01-22 10:33 UTC, theRealNG requested changes

2018-01-22 10:33 UTC, theRealNG commented on app/controllers/tasks_controller.rb
> +    @tagged_tasks = current_user.tagings.map{|tag| tag.task}
@rakesh-1010 Please write this logic in `User` model.

2018-01-22 10:33 UTC, theRealNG commented on app/controllers/tasks_controller.rb
> +    @tasks = (@my_tasks + @tagged_tasks).uniq.sort_by &:created_at
@rakesh-1010 I think it would be better to write a method in model like `user.all_tasks` which internally calls tasks created by user and tasks in which user has been tagged in.

2018-01-22 10:33 UTC, theRealNG commented on app/controllers/tasks_controller.rb
> +    @comment = @task.comments.build
@rakesh-1010 I think you can rename this as `new_comment` so that it is more readable.

2018-01-22 10:33 UTC, theRealNG commented on app/controllers/tasks_controller.rb
> +    create_tag(params[:tagged_user_id],params[:id]) if @taging.blank?
@rakesh-1010 This method should be at  model level.
`task.tag_user(user)`

2018-01-22 10:33 UTC, theRealNG commented on app/controllers/tasks_controller.rb
> +    remove_tag if @taging.present?
@rakesh-1010 This method should be at model level.
`task.untag_user(user)`


Might be you can handle untagging of old user in the `task.tag_user` itself i.e untag and old user if he is there and then tag new user to the task

2018-01-22 10:33 UTC, theRealNG commented on app/models/taging.rb
> +class Taging < ActiveRecord::Base
@rakesh-1010 The model name should be `Tag` as it contains list of tags for tasks.

2018-01-22 10:33 UTC, theRealNG commented on app/models/taging.rb
> +  def self.add_tag(user_id,task_id)
@rakesh-1010 You should create tag using `task.tags.new` rather then using this class method.

2018-01-22 10:33 UTC, theRealNG commented on app/models/taging.rb
> +  def remove_tag
@rakesh-1010 You should delete tag using `task.tag.destroy` rather than using this class method.

2018-01-22 10:33 UTC, theRealNG commented on app/models/user.rb
> +  has_many :tagings
@rakesh-1010 `has_many :tags`

2018-01-22 10:33 UTC, theRealNG commented on app/models/user.rb
> +  has_many :tasks
@rakesh-1010 You could add another assoication:
`has_many :tagged_tasks, through :tags`

2018-01-22 10:33 UTC, theRealNG commented on app/controllers/comments_controller.rb
> +    @task = @comment.task
@rakesh-1010 Not sure why u need `@task` here.

2018-01-22 10:33 UTC, theRealNG commented on app/controllers/comments_controller.rb
> +      @comment = Comment.find(params[:id])
@rakesh-1010 You should set the comment only using `@tasks.comments.find(params[:id])`

2018-01-22 10:33 UTC, theRealNG commented on spec/models/taging_spec.rb
> +  it "is valid with valid attributes", :skip_before => true do
@rakesh-1010 `it` statements should generally start with `should`. You can rewrite this as:
`it "should be valid if valid attributes are provided"`

2018-01-22 10:33 UTC, theRealNG commented on spec/models/taging_spec.rb
> +  describe "#remove_tag" do
@rakesh-1010 You could write this as contexts:
```
  describe :remove_tag do
    context "when user is already tagged" do
      it "should remove the tag"
    end

    context "when user is not already tagged" do
      it "should raise an error"
    end
  end
```

2018-02-02 04:40 UTC, merged